version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./orders.db
      - WEBHOOK_SECRET=devsecret
    volumes:
      - ./orders.db:/app/orders.db